#!/usr/bin/env python3
"""
pipeline/stage10_output.py
OpenClaw Pipeline — Stage 10: Output & Reporting
Agent: Elkin 🔱 | Version: 2.0
"""

import os
import csv
import json
import logging
import sqlite3
import requests
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

log = logging.getLogger("stage10_output")
REPORTS_DIR = Path("reports")
DB_PATH = Path("reports/sqlite/engagement.db")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "8069069638")


def _notify(message: str):
 if not TELEGRAM_BOT_TOKEN:
 return
 try:
 requests.post(
 f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage",
 json={"chat_id": TELEGRAM_CHAT_ID, "text": message},
 timeout=10
 )
 except Exception as e:
 log.error(f"Telegram notify failed: {e}")


def _write_json(data: dict, run_id: str) -> str:
 """Write full intelligence dump to JSON."""
 output_path = REPORTS_DIR / "json" / run_id / "full_report.json"
 output_path.parent.mkdir(parents=True, exist_ok=True)
 with open(output_path, "w") as f:
 json.dump(data, f, indent=2, default=str)
 log.info(f"JSON report: {output_path}")
 return str(output_path)


def _write_csv(data: dict, run_id: str) -> str:
 """Write discoveries to CSV."""
 output_path = REPORTS_DIR / "csv" / run_id / "discoveries.csv"
 output_path.parent.mkdir(parents=True, exist_ok=True)

 try:
 conn = sqlite3.connect(DB_PATH)
 c = conn.cursor()
 c.execute("""
 SELECT engagement_name, stage, type, value,
 confidence, source_tool, created_at
 FROM discoveries
 WHERE engagement_name = ?
 ORDER BY stage, type
 """, (data.get("engagement_name", "default"),))

 rows = c.fetchall()
 conn.close()

 with open(output_path, "w", newline="") as f:
 writer = csv.writer(f)
 writer.writerow([
 "engagement", "stage", "type", "value",
 "confidence", "tool", "timestamp"
 ])
 writer.writerows(rows)

 log.info(f"CSV report: {output_path} ({len(rows)} rows)")
 except Exception as e:
 log.error(f"CSV write error: {e}")

 return str(output_path)


def _write_markdown(data: dict, run_id: str,
 ai_summary: str) -> str:
 """Write human-readable markdown report."""
 output_path = REPORTS_DIR / "markdown" / run_id / "report.md"
 output_path.parent.mkdir(parents=True, exist_ok=True)

 stage1 = data.get("stage1", {})
 stage2 = data.get("stage2", {})
 stage3 = data.get("stage3", {})
 stage5 = data.get("stage5", {})
 stage8 = data.get("stage8", {})

 with open(output_path, "w") as f:
 f.write(f"# OpenClaw Engagement Report\n\n")
 f.write(f"**Agent:** Elkin 🔱 \n")
 f.write(f"**Target:** {data.get('target', 'N/A')} \n")
 f.write(f"**Engagement:** {data.get('engagement_name', 'N/A')} \n")
 f.write(
 f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} \n\n"
 )

 f.write("---\n\n## Executive Summary\n\n")
 f.write(ai_summary if ai_summary else "_AI synthesis unavailable_")
 f.write("\n\n---\n\n")

 f.write("## Findings Overview\n\n")
 f.write(
 f"| Category | Count |\n"
 f"|---|---|\n"
 f"| Subdomains | {len(stage1.get('subdomains_found', []))} |\n"
 f"| Emails | {len(stage1.get('emails_found', []))} |\n"
 f"| Live Hosts | {len(stage2.get('live_hosts', []))} |\n"
 f"| Open Ports | {len(stage2.get('open_ports', {}))} |\n"
 f"| URLs Discovered | {len(stage3.get('urls_discovered', []))} |\n"
 f"| Endpoints | {len(stage3.get('endpoints_found', []))} |\n"
 f"| Critical Secrets | {stage5.get('critical_count', 0)} |\n"
 f"| High Secrets | {stage5.get('high_count', 0)} |\n"
 f"| Breaches Found | {stage8.get('breach_count', 0)} |\n\n"
 )

 f.write("## Technology Stack\n\n")
 tech = stage2.get("tech_stack", {})
 if tech:
 for tech_name in list(tech.keys())[:20]:
 f.write(f"- {tech_name}\n")
 else:
 f.write("_No technology stack data_\n")

 f.write("\n## Open Ports\n\n")
 ports = stage2.get("open_ports", {})
 if ports:
 f.write("| Port | Service |\n|---|---|\n")
 for port, service in ports.items():
 f.write(f"| {port} | {service} |\n")
 else:
 f.write("_No open ports data_\n")

 f.write("\n---\n\n")
 f.write(
 "_Report generated by OpenClaw Pipeline v2.0 — Elkin 🔱_\n"
 )

 log.info(f"Markdown report: {output_path}")
 return str(output_path)


def run(target: str, config: dict) -> dict:
 """Stage 10 entry point."""
 log.info(f"{'='*60}")
 log.info(f"Stage 10 — Output & Reporting")
 log.info(f"Target: {target}")

 engagement = config.get("engagement_name", "default")
 all_findings = config.get("all_stage_findings", {})
 run_id = config.get("run_id", "default")
 ai_summary = all_findings.get("stage9", {}).get(
 "intelligence_summary", ""
 )

 report_data = {
 "target": target,
 "engagement_name": engagement,
 "run_id": run_id,
 "generated_at": datetime.utcnow().isoformat(),
 **all_findings
 }

 findings = {
 "stage": 10,
 "name": "OUTPUT",
 "target": target,
 "timestamp": datetime.utcnow().isoformat(),
 "tools_invoked": [],
 "report_files": {}
 }

 # JSON report
 json_path = _write_json(report_data, run_id)
 findings["report_files"]["json"] = json_path
 findings["tools_invoked"].append("json_reporter")

 # CSV report
 csv_path = _write_csv(report_data, run_id)
 findings["report_files"]["csv"] = csv_path
 findings["tools_invoked"].append("csv_reporter")

 # Markdown report
 md_path = _write_markdown(report_data, run_id, ai_summary)
 findings["report_files"]["markdown"] = md_path
 findings["tools_invoked"].append("markdown_reporter")

 # Final Telegram notification
 stage5 = all_findings.get("stage5", {})
 stage8 = all_findings.get("stage8", {})
 critical = stage5.get("critical_count", 0)
 high = stage5.get("high_count", 0)
 breaches = stage8.get("breach_count", 0)

 _notify(
 f"✅ [PIPELINE COMPLETE]\n"
 f"Target: {target}\n"
 f"Engagement: {engagement}\n"
 f"Critical secrets: {critical}\n"
 f"High secrets: {high}\n"
 f"Breaches: {breaches}\n"
 f"Reports: reports/*/{run_id}/"
 )

 log.info(
 f"Stage 10 complete — "
 f"JSON: {json_path}, "
 f"CSV: {csv_path}, "
 f"MD: {md_path}"
 )

 return findings
